platform :ios, '14.0'

target 'Plugin' do
  use_frameworks!
  pod 'Capacitor'
  pod 'GCDWebServer', '~> 3.5'
end

target 'PluginTests' do
  use_frameworks!
  pod 'Capacitor'
  pod 'GCDWebServer', '~> 3.5'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force Swift and iOS version
      config.build_settings['SWIFT_VERSION'] = '5.10'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'YES'
      # config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'

      # Fix embed Swift libs warning for test target
      if target.name.include?("Tests")
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
      end
    end
  end
end
